### ISSUE TITLE
the results is not full

### ISSUE THREAD

**Issue by tan5251** [feliixx/gotranseq#5]
i have 2840 uniq dna sequence, but the results only output 1930 rows with default. It makes me  very puzzled.

**Comment by feliixx** [comment]
Hi @tan5251, 

can you share your fasta file, or a way to reproduce this issue ? And what options did you used ?

**Comment by tan5251** [comment]
I have sent my fasta file to your email. Please check it. Thanks a lot gotranseq_1/gotranseq -s xxx.fasta -o xxxx.fasta -f 6

**Comment by tan5251** [comment]
Hi. Thanks for you reply. Here is the download address of my files. Please help me to&nbsp; check it. My codes is followed default&nbsp; (gotranseq_1/gotranseq -s xxx.fasta -o xxxx.fasta -f 6 ).&nbsp; &nbsp;https://we.tl/t-IEJyOOvQOo




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "feliixx/gotranseq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月9日(星期五) 中午11:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [feliixx/gotranseq] the results is not full (#5)





 
Hi @tan5251,
 
can you share your fasta file, or a way to reproduce this issue ? And what options did you used ?

**Comment by feliixx** [comment]
looks like it crashed because one of the sequence was too big ( `MSTRG.206.1::1:28193005-28285792(-)` ) 
I've updated the max size allowed for a sequence, it should work fine with the new version: [release v0.3.1](https://github.com/feliixx/gotranseq/releases/tag/v0.3.1)

**Comment by tan5251** [comment]
Hi, it works well by the new version of gotranseq. Thanks again.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "feliixx/gotranseq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月9日(星期五) 下午2:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [feliixx/gotranseq] the results is not full (#5)





 
looks like it crashed because one of the sequence was too big ( MSTRG.206.1::1:28193005-28285792(-) )
 I've updated the max size allowed for a sequence, it should work fine with the new version: release v0.3.1
