### ISSUE TITLE
lower case fasta seqeunces no recognised

### ISSUE THREAD

**Issue by DeenSm** [feliixx/gotranseq#9]
Hi Feliix, 

thanks for gotranseq, I've hit an issue with some of my fasta DNA sequences being in lower case letters whcih are all replaced with 'N' (see below), and I end up with no translation for that sequence. Is this something you can rectify in the future?

WARNING: invalid char in sequence >sakai_stx2a-A.fasta: 't' ( pos 503), replacing with 'N'

Thanks,

DeenSm

**Comment by feliixx** [comment]
Hi @DeenSm, thanks for reporting this! 
I've just created a new release (https://github.com/feliixx/gotranseq/releases/tag/v0.4.0) that should correctly handle lowercase fasta.
